import { sql } from '../sql'

// ============================================================
// Setlist Song Types and Functions
// ============================================================

export type SongType = 'cover' | 'mashup' | 'medley' | 'transition'
export type SetlistStatus = 'pending' | 'locked' | 'conflict'

export interface AdditionalSong {
  title: string
  artist: string
}

export interface SetlistSong {
  id: string
  band_id: string
  position: number
  song_type: SongType
  title: string
  artist: string
  additional_songs: AdditionalSong[]
  transition_to_title: string | null
  transition_to_artist: string | null
  youtube_video_id: string | null
  status: SetlistStatus
  artist_description: string | null
  spotify_track_id: string | null
  created_at: string
  updated_at: string
  // Joined fields (from band -> event)
  band_name?: string
  event_id?: string
  event_name?: string
  event_date?: string
  company_slug?: string
  company_name?: string
  company_icon_url?: string
}

export interface SetlistSongInput {
  id: string // UUIDv7 generated by caller
  band_id: string
  position: number
  song_type: SongType
  title: string
  artist: string
  additional_songs?: AdditionalSong[]
  transition_to_title?: string
  transition_to_artist?: string
  youtube_video_id?: string
  status?: SetlistStatus
  artist_description?: string
  spotify_track_id?: string
}

/**
 * Get all setlist songs for a band
 */
export async function getSetlistForBand(
  bandId: string
): Promise<SetlistSong[]> {
  try {
    const { rows } = await sql<SetlistSong>`
      SELECT s.*, 
             b.name as band_name,
             b.event_id,
             e.name as event_name,
             e.date as event_date,
             b.company_slug,
             c.name as company_name,
             c.icon_url as company_icon_url
      FROM setlist_songs s
      JOIN bands b ON s.band_id = b.id
      JOIN events e ON b.event_id = e.id
      LEFT JOIN companies c ON b.company_slug = c.slug
      WHERE s.band_id = ${bandId}
      ORDER BY s.position ASC
    `
    return rows
  } catch (error) {
    console.error('Error fetching setlist for band:', error)
    throw error
  }
}

/**
 * Get all setlist songs for an event (all bands)
 */
export async function getSetlistsForEvent(
  eventId: string
): Promise<SetlistSong[]> {
  try {
    const { rows } = await sql<SetlistSong>`
      SELECT s.*, 
             b.name as band_name,
             b.event_id,
             e.name as event_name,
             e.date as event_date,
             b.company_slug,
             c.name as company_name,
             c.icon_url as company_icon_url
      FROM setlist_songs s
      JOIN bands b ON s.band_id = b.id
      JOIN events e ON b.event_id = e.id
      LEFT JOIN companies c ON b.company_slug = c.slug
      WHERE b.event_id = ${eventId}
      ORDER BY b."order" ASC, s.position ASC
    `
    return rows
  } catch (error) {
    console.error('Error fetching setlists for event:', error)
    throw error
  }
}

/**
 * Get all setlist songs across all events (for the /songs page)
 */
export interface GetAllSongsOptions {
  eventId?: string
  bandId?: string
  songType?: SongType
  search?: string
  limit?: number
  offset?: number
}

export async function getAllSongs(
  options: GetAllSongsOptions = {}
): Promise<SetlistSong[]> {
  const { eventId, bandId, songType, search, limit = 100, offset = 0 } = options

  try {
    // Build search pattern if provided
    const searchPattern = search ? `%${search}%` : null

    const { rows } = await sql<SetlistSong>`
      SELECT s.*, 
             b.name as band_name,
             b.event_id,
             e.name as event_name,
             e.date as event_date,
             b.company_slug,
             c.name as company_name,
             c.icon_url as company_icon_url
      FROM setlist_songs s
      JOIN bands b ON s.band_id = b.id
      JOIN events e ON b.event_id = e.id
      LEFT JOIN companies c ON b.company_slug = c.slug
      WHERE 
        (${eventId || null}::text IS NULL OR b.event_id = ${eventId || null})
        AND (${bandId || null}::text IS NULL OR s.band_id = ${bandId || null})
        AND (${songType || null}::text IS NULL OR s.song_type = ${songType || null})
        AND (
          ${searchPattern}::text IS NULL 
          OR s.title ILIKE ${searchPattern || ''}
          OR s.artist ILIKE ${searchPattern || ''}
          OR s.transition_to_title ILIKE ${searchPattern || ''}
          OR s.transition_to_artist ILIKE ${searchPattern || ''}
        )
      ORDER BY e.date DESC, b."order" ASC, s.position ASC
      LIMIT ${limit} OFFSET ${offset}
    `
    return rows
  } catch (error) {
    console.error('Error fetching all songs:', error)
    throw error
  }
}

/**
 * Get total count of songs with optional filters
 */
export async function getSongCount(
  options: Omit<GetAllSongsOptions, 'limit' | 'offset'> = {}
): Promise<number> {
  const { eventId, bandId, songType, search } = options
  const searchPattern = search ? `%${search}%` : null

  try {
    const { rows } = await sql<{ count: string }>`
      SELECT COUNT(*) as count
      FROM setlist_songs s
      JOIN bands b ON s.band_id = b.id
      WHERE 
        (${eventId || null}::text IS NULL OR b.event_id = ${eventId || null})
        AND (${bandId || null}::text IS NULL OR s.band_id = ${bandId || null})
        AND (${songType || null}::text IS NULL OR s.song_type = ${songType || null})
        AND (
          ${searchPattern}::text IS NULL 
          OR s.title ILIKE ${searchPattern || ''}
          OR s.artist ILIKE ${searchPattern || ''}
          OR s.transition_to_title ILIKE ${searchPattern || ''}
          OR s.transition_to_artist ILIKE ${searchPattern || ''}
        )
    `
    return parseInt(rows[0]?.count || '0', 10)
  } catch (error) {
    console.error('Error counting songs:', error)
    throw error
  }
}

/**
 * Create a new setlist song
 */
export async function createSetlistSong(
  song: SetlistSongInput
): Promise<SetlistSong> {
  try {
    const additionalSongsJson = JSON.stringify(song.additional_songs || [])

    const { rows } = await sql<SetlistSong>`
      INSERT INTO setlist_songs (
        id, band_id, position, song_type, title, artist,
        additional_songs, transition_to_title, transition_to_artist,
        youtube_video_id, artist_description, spotify_track_id, status
      )
      VALUES (
        ${song.id}, ${song.band_id}, ${song.position}, ${song.song_type},
        ${song.title}, ${song.artist}, ${additionalSongsJson}::jsonb,
        ${song.transition_to_title || null}, ${song.transition_to_artist || null},
        ${song.youtube_video_id || null}, ${song.artist_description || null},
        ${song.spotify_track_id || null}, ${song.status || 'pending'}
      )
      RETURNING *
    `
    return rows[0]
  } catch (error) {
    console.error('Error creating setlist song:', error)
    throw error
  }
}

/**
 * Update an existing setlist song
 */
export async function updateSetlistSong(
  songId: string,
  updates: Partial<Omit<SetlistSongInput, 'id' | 'band_id'>>
): Promise<SetlistSong | null> {
  try {
    const additionalSongsJson = updates.additional_songs
      ? JSON.stringify(updates.additional_songs)
      : null

    const { rows } = await sql<SetlistSong>`
      UPDATE setlist_songs SET
        position = COALESCE(${updates.position ?? null}, position),
        song_type = COALESCE(${updates.song_type || null}, song_type),
        title = COALESCE(${updates.title || null}, title),
        artist = COALESCE(${updates.artist || null}, artist),
        additional_songs = COALESCE(${additionalSongsJson}::jsonb, additional_songs),
        transition_to_title = ${updates.transition_to_title === undefined ? null : updates.transition_to_title},
        transition_to_artist = ${updates.transition_to_artist === undefined ? null : updates.transition_to_artist},
        youtube_video_id = ${updates.youtube_video_id === undefined ? null : updates.youtube_video_id},
        artist_description = ${updates.artist_description === undefined ? null : updates.artist_description},
        spotify_track_id = ${updates.spotify_track_id === undefined ? null : updates.spotify_track_id},
        status = COALESCE(${updates.status || null}, status),
        updated_at = NOW()
      WHERE id = ${songId}
      RETURNING *
    `
    return rows[0] || null
  } catch (error) {
    console.error('Error updating setlist song:', error)
    throw error
  }
}

/**
 * Delete a setlist song
 */
export async function deleteSetlistSong(
  songId: string
): Promise<SetlistSong | null> {
  try {
    const { rows } = await sql<SetlistSong>`
      DELETE FROM setlist_songs WHERE id = ${songId}
      RETURNING *
    `
    return rows[0] || null
  } catch (error) {
    console.error('Error deleting setlist song:', error)
    throw error
  }
}

/**
 * Reorder setlist songs for a band
 * Takes an array of song IDs in the desired order
 */
export async function reorderSetlistSongs(
  bandId: string,
  songIds: string[]
): Promise<void> {
  try {
    // Update each song's position based on its index in the array
    for (let i = 0; i < songIds.length; i++) {
      await sql`
        UPDATE setlist_songs 
        SET position = ${i + 1}, updated_at = NOW()
        WHERE id = ${songIds[i]} AND band_id = ${bandId}
      `
    }
  } catch (error) {
    console.error('Error reordering setlist songs:', error)
    throw error
  }
}

/**
 * Detect song conflicts within an event
 * Returns songs that appear in multiple bands' setlists
 */
export interface SongConflict {
  title: string
  artist: string
  bands: { band_id: string; band_name: string; song_id: string }[]
}

export async function detectSongConflicts(
  eventId: string
): Promise<SongConflict[]> {
  try {
    // Find songs with the same title+artist across different bands in the event
    const { rows } = await sql<{
      title: string
      artist: string
      band_id: string
      band_name: string
      song_id: string
    }>`
      SELECT s.title, s.artist, s.band_id, b.name as band_name, s.id as song_id
      FROM setlist_songs s
      JOIN bands b ON s.band_id = b.id
      WHERE b.event_id = ${eventId}
        AND (LOWER(s.title), LOWER(s.artist)) IN (
          SELECT LOWER(s2.title), LOWER(s2.artist)
          FROM setlist_songs s2
          JOIN bands b2 ON s2.band_id = b2.id
          WHERE b2.event_id = ${eventId}
          GROUP BY LOWER(s2.title), LOWER(s2.artist)
          HAVING COUNT(DISTINCT s2.band_id) > 1
        )
      ORDER BY s.title, s.artist, b."order"
    `

    // Group by title+artist
    const conflictMap = new Map<string, SongConflict>()
    for (const row of rows) {
      const key = `${row.title.toLowerCase()}|${row.artist.toLowerCase()}`
      if (!conflictMap.has(key)) {
        conflictMap.set(key, {
          title: row.title,
          artist: row.artist,
          bands: [],
        })
      }
      conflictMap.get(key)!.bands.push({
        band_id: row.band_id,
        band_name: row.band_name,
        song_id: row.song_id,
      })
    }

    return Array.from(conflictMap.values())
  } catch (error) {
    console.error('Error detecting song conflicts:', error)
    throw error
  }
}

/**
 * Update conflict status for songs in an event
 * Call this after adding/updating songs to mark conflicts
 */
export async function updateConflictStatus(eventId: string): Promise<void> {
  try {
    // First, reset all songs in the event to their non-conflict status
    await sql`
      UPDATE setlist_songs s
      SET status = CASE WHEN s.status = 'conflict' THEN 'pending' ELSE s.status END,
          updated_at = NOW()
      FROM bands b
      WHERE s.band_id = b.id AND b.event_id = ${eventId}
    `

    // Then, mark conflicts
    const conflicts = await detectSongConflicts(eventId)
    for (const conflict of conflicts) {
      for (const band of conflict.bands) {
        await sql`
          UPDATE setlist_songs
          SET status = 'conflict', updated_at = NOW()
          WHERE id = ${band.song_id}
        `
      }
    }
  } catch (error) {
    console.error('Error updating conflict status:', error)
    throw error
  }
}

/**
 * Lock all songs for a band (mark as finalized)
 */
export async function lockBandSetlist(bandId: string): Promise<void> {
  try {
    await sql`
      UPDATE setlist_songs
      SET status = 'locked', updated_at = NOW()
      WHERE band_id = ${bandId} AND status != 'conflict'
    `
  } catch (error) {
    console.error('Error locking band setlist:', error)
    throw error
  }
}

/**
 * Unlock all songs for a band (return to pending)
 */
export async function unlockBandSetlist(bandId: string): Promise<void> {
  try {
    await sql`
      UPDATE setlist_songs
      SET status = 'pending', updated_at = NOW()
      WHERE band_id = ${bandId}
    `
  } catch (error) {
    console.error('Error unlocking band setlist:', error)
    throw error
  }
}

/**
 * Get all performances of a specific song (by title and artist).
 * Returns all instances where this song was performed across events/bands.
 * Searches primary title/artist, transition_to_title/artist, and additional_songs.
 */
export async function getSongPerformances(
  title: string,
  artist: string
): Promise<SetlistSong[]> {
  try {
    const lowerTitle = title.toLowerCase()
    const lowerArtist = artist.toLowerCase()

    // Search across primary, transition_to, and additional_songs
    const { rows } = await sql<SetlistSong>`
      SELECT s.*, 
             b.name as band_name,
             b.event_id,
             e.name as event_name,
             e.date as event_date,
             b.company_slug,
             c.name as company_name,
             c.icon_url as company_icon_url
      FROM setlist_songs s
      JOIN bands b ON s.band_id = b.id
      JOIN events e ON b.event_id = e.id
      LEFT JOIN companies c ON b.company_slug = c.slug
      WHERE 
        -- Match primary title/artist
        (LOWER(s.title) = ${lowerTitle} AND LOWER(s.artist) = ${lowerArtist})
        -- Match transition_to title/artist
        OR (LOWER(s.transition_to_title) = ${lowerTitle} AND LOWER(s.transition_to_artist) = ${lowerArtist})
        -- Match in additional_songs array (JSONB search)
        OR EXISTS (
          SELECT 1 FROM jsonb_array_elements(s.additional_songs) AS elem
          WHERE LOWER(elem->>'title') = ${lowerTitle}
            AND LOWER(elem->>'artist') = ${lowerArtist}
        )
      ORDER BY e.date DESC, b.name ASC
    `
    return rows
  } catch (error) {
    console.error('Error fetching song performances:', error)
    throw error
  }
}
