import type { Metadata } from "next";
import { Rock_Salt, Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { FacebookPixel } from "@/components/facebook-pixel";

const rockSalt = Rock_Salt({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rock-salt",
});

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${rockSalt.variable} ${lato.variable} font-sans antialiased bg-bg text-text`}
        suppressHydrationWarning={true}
      >
        <Providers>{children}</Providers>
        <Analytics />
        <SpeedInsights />
        <FacebookPixel />
      </body>
    </html>
  );
}
